rabbitmq:
  container_name: rabbitmq
  image: rabbitmq:latest
  hostname: "rabbitmq"
  net: artemis

artemis:
  container_name: artemis
  image: navitia/debian8_artemis:latest
  hostname: "artemis"
  volumes_from: 
    - rabbitmq
  ports:
    - 8080:80
  net: artemis

artemis_db:
  container_name: artemis_db
  image: navitia/artemis_db:latest
  stdin_open: true
  hostname: "artemis_db"
  net: artemis
