# Read README.md before launching

# http://stackoverflow.com/questions/27670828/fig-up-docker-containers-start-synchronisation
rabbitmq:
  container_name: rabbitmq
  image: rabbitmq:latest
  hostname: "rabbitmq"

artemis:
  container_name: artemis
  image: navitia/debian8_artemis:latest
  hostname: "artemis"
  volumes_from: 
    - rabbitmq
  ports:
    - 8080:80

artemis_db:
  container_name: artemis_db
  image: navitia/artemis_db:latest
  stdin_open: true
  hostname: "artemis_db"

